import "./globals.css";
import "./index.scss";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}

const Navbar = () => {
  return (
    <>
      <Link href="/">
        <p>home</p>
      </Link>
      <Link href="/login">
        <p>Login</p>
      </Link>
    </>
  );
};
