import "./globals.css";
import "./index.scss";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import Link from "next/link";
import { UserContextProvider } from "@/context/userContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  if (typeof window !== "undefined") {
    // Perform localStorage action
    const item = localStorage.getItem("token-user");
    console.log("item", item);
  }
  return (
    <html lang="en">
      <UserContextProvider>
        <body className={inter.className}>
          <Navbar />
          {children}
        </body>
      </UserContextProvider>
    </html>
  );
}

const Navbar = () => {
  return (
    <>
      <Link href="/">
        <p>home</p>
      </Link>
      <Link href="/login">
        <p>Login</p>
      </Link>
    </>
  );
};
